name: Node.js CI

on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Install and Build 
        run: |
          npm install
          CI=false npm run build

      - name: Deploy 
        uses: actions/checkout@v4 
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build